purescript-spec/purescript-spec

bower.json
src/Test/Spec.purs
src/Test/Spec/Reporter.purs

PureScript 0.7.2 seems to have added warnings for redundancy and incompleteness in case statements.

Fix case statements to remove warnings for 0.7.2

---

src/Test/Spec/Runner.purs

Behaviour was already there for failure, now also for success.
For integration tests. If there are connections open, NodeJS won't exit.
e.g.
http://stackoverflow.com/questions/18046639/node-process-doesnt-exit-after-firebase-once
I don't know how to write a test for this at the moment, since the
behaviour does an 'exit 0'.

Exit NodeJS process on success as well as failure.

---

src/Test/Spec/Runner.purs
test/Main.purs

All the purescript core libraries use UPPERCASE names for effects.

Adopt the uppercase convention for the process effect name.

---

bower.json

Changed all dependencies to use '^' instead of '>=', so bower does not
go searching for 1.0.0 packages and their dependencies.
Also bumped version to 0.7.5, so this can go on to bower soon,
hopefully.
(I finally read:
https://github.com/npm/node-semverhttps://github.com/npm/node-semver
).
It looks like the build (and a local install) failed because one of our
dependencies' dependencies does not yet exist in the right version.
Separate minor version, so things that depend on this (two of my
packages) that can't yet be upgraded because not all their (transitive)
dependencies exist in the right version yet.
I guess upgrading to all 1.0.0+ dependencies should be done in a version
of purescript-spec that is also 1.0.0?

Depend on all packages < 1.0.0, bump to 0.7.5

---

src/Test/Spec.purs
src/Test/Spec/Reporter.purs
src/Test/Spec/Runner.purs
src/Test/Spec/Summary.purs
test/Test/Spec/Fixtures.purs
test/Test/Spec/RunnerSpec.purs

Implement to new functions `describeOnly` and `itOnly` that will cause all other tests to be culled.
This is useful for quickly testing a subset of tests.
Refer to #16 for details.

Implement the ".only" modifier from mocha

---

src/Test/Spec/Color.purs

Gray is invisible on the Solarized theme. Dim achieves a similar effect.
Dim is not supported on Windows but will be ignored afaik, rather than making the text invisible.
See https://github.com/eslint/eslint/pull/4885 for explanation and pictures.

Use 'dim' code in place of 'gray'

---

.travis.yml
bower.json
example/Main.purs
src/Test/Spec/Assertions.purs
test/Test/Spec/RunnerSpec.purs

Needed for https://github.com/purescript-contrib/purescript-unicode/pull/8
Still needs `purescript-pipes` and `purescript-node-process` to be brought to 0.11

Updates for 0.11

---

src/Test/Spec.purs

from [website](http://purescript-spec.wickstrom.tech/)
> Pending specs can also contain a spec body, just like with it. The difference is that the body will be ignored. Pending spec bodies are used to give a hint what the spec should assert in the future. Use pending' (note the ' at the end) to create a pending spec with a body.
> 
> ``` purescript
> pending' "calculates the answer to Life, the Universe and Everything" do
>   answerTo theUltimateQuestion `shouldBe` 42
> ```
but it's not exported

export pending'

---

docs/running.md

I see this recommends compiling to output/tests. If doing that, the compilation wouldn't be able to use previously compilation artifacts as cached results to shorten compile times. I think we can safely compile to "output", no?

Compile tests to output, not output/tests

---

bower.json
src/Test/Spec.purs
src/Test/Spec/Runner.purs

Sorry for just opening a PR without a specific issue. Related to #61.
`delay` seems to do what we want.
We can avoid a JS specific dependency by using `delay`.

Remove `-js-timers`

---

src/Test/Spec/Runner.purs

https://github.com/purescript-spec/purescript-spec/commit/da88e3cd14df721c93b7f48b65ce896e89e1df5e#diff-6284d4c18f32617e31426063da6476aeR170 introduced a bug: it makes the test suite exit with a success exit code on failure, and with a failure exit code on success.

Flip exit codes to the correct ones

---

docs/index.html
docs/running.md
docs/writing-specs.md
src/Test/Spec/Runner.purs
test/Main.purs

Since `run :: Effect Unit` would return immediately and then run on the side - it would be better if our entrypoint was to return `Aff Unit` which can then be awaited.
The drawback is that users will now have broken code and have to include `launchAff_` when running their main:
```haskell
main :: Effect Unit
main = launchAff_ $ run [ consoleReporter ] do ...
```
This fixes @Dretch's issue with xunit.
Thoughts, @owickstrom ?

Redefine `run` and `run'` to return `Aff Unit`

---

Makefile

As I mentioned in #95, Pandoc options have changed since the Makefile was written. The CLI was clear about updating ```--chapters``` to ```--top-level-division=chapter```; but it was less clear what to do with the ```-S``` option. However, the [Pandoc User's Guide](https://pandoc.org/MANUAL.html) doesn't list ```html5``` (or ```html```) in the list of formats that support the ```smart``` extension that was previously enabled with ```-S```.

Update Pandoc options; resolves #95.

---

docs/running.md

Types for timeout and slow were not correct
https://github.com/purescript-spec/purescript-spec/blob/a91d77654c4a6ac314b42bae941892dd576c4916/src/Test/Spec/Runner.purs#L52-L64

Docs: Fix test configuration example types

---

.travis.yml

Turns out the Travis script was specifically installing PS 0.12.0, so the build failed after updating dependencies.
I wonder why it didn't fail on the pull request though?..

Fix Travis script for PS 0.14

---

src/Test/Spec/Reporter/Base.purs
src/Test/Spec/Reporter/Console.purs
src/Test/Spec/Reporter/Spec.purs
src/Test/Spec/Result.purs
src/Test/Spec/Runner.purs

Removes unused names, which now warn as of PureScript 0.14.1.

Remove unused names

---

docs/writing-specs.md

I believe the PureScript binding rules makes for () surrounding 1 + 1. At least that is what made my test code compile after scratching head from this error message:
```at test/Main.purs:16:9 - 16:26 (line 16, column 9 - line 16, column 26)
Could not match type
t0 Unit
with type
Int
while checking that type t0 Unit
is at least as general as type Int
while checking that expression (shouldEqual 1) 2
has type Int
in value declaration main
where t0 is an unknown type
```

Parenthesis missing?

---

src/Test/Spec/Reporter/TeamCity.purs
test/Test/Spec/Reporter/TeamCitySpec.purs

The teamcity reporter now reports id for the node and its parent so that the tool reading the output don't need to ques anymore through nesting. This means that it should have full support for parallel test runs.
bellow is a example of the tests running in intellij with the new changes
https://user-images.githubusercontent.com/72190/211170814-3ea8f6b1-21db-4ab0-bd46-7284ffcc5b44.mp4

Support parallell teamcity

---

src/Test/Spec/Reporter/TeamCity.purs

Adding metadata to the teamcity service message allows intellij to show diff window for should equals expection

Add diff support for teamcity reporter

---

integration-tests/cases/01-all-passing/output.txt
integration-tests/cases/02-all-failing/output.txt
integration-tests/cases/03-some-passing/output.txt
integration-tests/cases/04-fail-fast-with-timeout/output.txt
integration-tests/cases/05-fail-fast-due-to-test-failure/output.txt
src/Test/Spec.purs
src/Test/Spec/Config.purs
src/Test/Spec/Reporter/Base.purs
src/Test/Spec/Reporter/Console.purs
src/Test/Spec/Runner.purs
src/Test/Spec/Runner/Event.purs
src/Test/Spec/Summary.purs
src/Test/Spec/Tree.purs
test/Integration.purs
test/Test/Spec/RunnerSpec.purs

* The `Tree` type now has an extra parameter denoting annotation of each node. Previously this was always `String` (meaning name), now it's a parameter.
* Extracted the logic of computing paths from `run_` and `printFailures`, named it `annotateWithPaths`. Replaces node names with pairs name+path.
* Added a generalized `filterTree` function, rephrased `discradUnfocused` in terms of `filterTree`.
* New config parameter - `filterTree`. The runner passes the test tree through it before execution.

Support for filtering the test tree

---

Makefile
integration-tests/cases/04-fail-fast-with-timeout/output.txt
integration-tests/cases/05-fail-fast-due-to-test-failure/output.txt
spago.dhall
src/Test/Spec/Runner.purs
test/Test/Spec/RunnerSpec.purs

The original implementation in #137 was a bit lazy: due to accidental complexity, it was very hard to return the whole test tree if the execution was stopped on first failure. However, down the stack it turned out that we do need the full tree after all, so this PR makes it happen. 
Instead of a downstream filtering pipe, the `failFast` option is now checked during the tree traversal, and a mutable cell is used to indicate when the execution ought to stop. When that mutable flag is set, the tree traversal itself still runs to the end, producing the full tree, even though the actual example execution gets skipped. Accordingly, in that case, skipped tests will show up in the results as "pending".
The mutable cell is used instead of a, say, `StateT`, because of parallelization, which doesn't …

Better support for fail-fast

---

bower.json

Moves test dependencies into the proper field for the `bower.json` file. This unblocks the issue I discovered here: https://github.com/purescript-node/purescript-node-streams/pull/54#issuecomment-1641124942
Deps were determined by looking at `test.dhall`.

Move `bower.json` test deps into `devDependencies` field

---

integration-tests/cases/issue-144-console-reporter-single-level-nesting/Main.purs
integration-tests/cases/issue-144-console-reporter-single-level-nesting/output.txt
src/Test/Spec/Reporter/Console.purs

Fixes #144 
When printing the just-finished test, `consoleReporter` decides whether to print the suite name before it or not. To make the decision, the reporter looks at the last suite name it printed: if it's different from the current one, print it, otherwise - skip.
The problem was, it wasn't comparing the full suite name, but only the N-1 prefix of it. As a result, it required a minimum of two levels of suites change from test to test in order to print the suite.

Console reporter should look at full path when deciding whether to print suite

---

integration-tests/cases/issue-149-async-tests/Main.purs
integration-tests/cases/issue-149-async-tests/output.txt
src/Test/Spec/Reporter/Base.purs
src/Test/Spec/Reporter/Console.purs
src/Test/Spec/Reporter/Dot.purs
src/Test/Spec/Reporter/Spec.purs
src/Test/Spec/Reporter/Tap.purs
src/Test/Spec/Reporter/TeamCity.purs
src/Test/Spec/Runner.purs
src/Test/Spec/Runner/Event.purs
src/Test/Spec/Tree.purs
test/Test/Spec/RunnerSpec.purs

Fixes #149 
It turns out reporting of parallelized tests has been broken for a while due to the `path` no longer being the full path, but only the "parent" path of the test item in question.
In this PR I am bringing a bit more standardization to this area, creating a new type `TestLocator = Path /\ Name` and converting relevant places to using it.
I'm not sure this is optimal. Perhaps `Path` alone should be used as a tree-scoped ID of a test. But this is also a bit inconsistent, because some types explicitly include the test name. Need to think about it some more.

Fix Reporter.Base.defaultUpdate handling of parallel execution
